add dsu to plugins that use the api
DiscordSRV/Documentation pull request #34
Opened 2022-12-06 19:39 UTC by BlueTree242

2022-12-07 22:31 UTC, granny requested changes
Either the plugin name needs to be changed to not include "DiscordSRV" or a disclaimer must be added stating it's not associated with DiscordSRV at all.

2022-12-07 22:31 UTC, granny commented on docs/index.md
> +* [DiscordSRVUtils Addon](https://discordsrvutils.xyz/)
```suggestion
* [DiscordSRVUtils Addon](https://www.spigotmc.org/resources/discordsrvutils.85958/)
```
The website is currently down. I don't trust it to be up 24/7 so I'd appreciate if the url was replaced with the spigot resource page.

2022-12-08 04:53 UTC, BlueTree242 commented
> Either the plugin name needs to be changed to not include "DiscordSRV" or a disclaimer must be added stating it's not associated with DiscordSRV at all.

There is a disclaimer at the bottom of each spigot page and website

2022-12-08 05:04 UTC, BlueTree242 commented
![image](https://user-images.githubusercontent.com/69328929/206361191-c24ae4e9-7284-4b3c-8189-a19170ff6dad.png)

2022-12-17 11:24 UTC, BlueTree242 commented
hello?

2023-01-22 08:37 UTC, granny commented
closing since I can't push changes to repos that are behind organizations. superceded by https://github.com/DiscordSRV/Documentation/commit/926572923a400428a08e71100e1b25664667b78e

2023-01-22 08:37 UTC, closed without merging