Revamp docs
DiscordSRV/Documentation pull request #67
Opened 2024-06-28 23:24 UTC by Bermiin

Made docs be more up-to-date. Commits themselves describe what I've actually done

2024-06-29 15:27 UTC, Dinty1 requested changes
Overall LGTM just one nitpick

2024-06-29 15:27 UTC, Dinty1 commented on docs/alerts.mdx
> +* https://github.com/ANutley/LuckPermsAlerts
This should probably also go under the Luckperms heading

2024-06-30 16:19 UTC, ANutley requested changes

2024-06-30 16:19 UTC, ANutley commented on docs/installation/initial-setup.mdx
> +Go to your Discord settings by clicking on the `User Settings` wheel on the bottom left of your Discord.
```suggestion
Go to your Discord settings by clicking on the `User Settings` cog on the bottom left of your Discord.
```

2024-06-30 16:19 UTC, ANutley commented on docs/installation/initial-setup.mdx
> +Go to the `Roles` tab and create a new role. We've named ours `Bot`. Add the `Administrator` permission (or [permissions listed below](#server-permissions)) to the new role.
```suggestion
Go to the `Roles` tab and create a new role. We've named ours `Bot`. Add the `Administrator` permission (or the [permissions listed below](#server-permissions)) to the new role.
```

2024-06-30 16:19 UTC, ANutley commented on docs/installation/initial-setup.mdx
> +![Add Bot-rule to bot](/assets/add_role.gif)
I know this was how it was originally, but this is surely supposed to say bot right?
```suggestion
![Add Bot-role to bot](/assets/add_role.gif)
```

2024-06-30 16:19 UTC, ANutley commented on docs/installation/sync-setup.md
> +
Perhaps make this a drop down with a title like "Using LuckPerms for groups?" and then specify that the display name is used, stating that its the one in brackets.

2024-06-30 16:19 UTC, ANutley commented on docs/installation/sync-setup.md
> +# synchronization.yml Line 36
(https://github.com/DiscordSRV/DiscordSRV/blob/develop/src/main/resources/synchronization/en.yml#L37)
```suggestion
# synchronization.yml Line 37
```

2024-06-30 16:57 UTC, Bermiin commented on docs/alerts.mdx
> +              Description: "`${#event.getEvent().getTarget().getFriendlyName()}` has had the group `${#event.getEvent().getNode().getGroupName()}` set to `${#event.getEvent().getNode().getValue()}`"
https://github.com/LuckPerms/LuckPerms/blob/master/api%2Fsrc%2Fmain%2Fjava%2Fnet%2Fluckperms%2Fapi%2Fnode%2Ftypes%2FInheritanceNode.java#L54

2024-06-30 17:00 UTC, ANutley commented on docs/alerts.mdx
> +              Description: "`${#event.getEvent().getTarget().getFriendlyName()}` has had the group `${#event.getEvent().getNode().getGroupName()}` set to `${#event.getEvent().getNode().getValue()}`"
My bad, was looking at the docs for the general node, not the inheritance node

2024-07-02 11:09 UTC, granny requested changes
1. I kind of liked the Minecraft Hero Academia "joke" that persisted throughout each screenshot. I appreciate the updated images, but if they could be changed back to keep that going, that'd be nice.
2. This one PR could very well have been split up into multiple smaller PRs.
   1. adding the LuckPerms alerts (would have been updated and merged)
   2. Updating the docs with missed config options (would have been merged)
   3. Removing outdated config options (would have been merged if not for https://github.com/DiscordSRV/Documentation/pull/68)
   4. Updating images & word adjustments
   5. Fixing the permissions table (`would have been merged)

    A good chunk of changes could have been merged already but they are being blocked because of 1 unrelated change.
3. Please create a new branch for every PR you create. This is a good habit to have, as well as allows for you to create multiple PRs targeted towards a specific branch without any issues.
4. Look at my other comments

2024-07-08 14:33 UTC, Bermiin commented
Gonna close this and redo it properly.

2024-07-08 14:33 UTC, closed without merging